rewards = [
    100,
    250,
    1000,
    5000,
    10000,
    50000
]

nudes = [
    ":eggplant:",
    ":peach:",
    "http://i.imgur.com/iLqTx9V.jpg",
    "http://i.imgur.com/H8y0ukS.jpg",
    "http://i.imgur.com/9fCCSQ2.jpg",
    "http://i.imgur.com/DDvRl4F.jpg",
]

repl = [
    [" ",  "_"],
    ["-",  "--"],
    ["?",  "~q"],
    ["%",  "~p"],
    ["''", "\""]
]

memes = [
    "tenguy",
    "afraid",
    "older",
    "aag",
    "tried",
    "biw",
    "blb",
    "kermit",
    "bd",
    "ch",
    "cbg",
    "wonka",
    "cb",
    "keanu",
    "dsm",
    "live",
    "ants",
    "doge",
    "alwaysonbeat",
    "ermg",
    "fwp",
    "fa",
    "fbf",
    "fmr",
    "fry",
    "ggg",
    "hipster",
    "icanhas",
    "crazypills",
    "regret",
    "boat",
    "sohappy",
    "captain",
    "inigo",
    "iw",
    "ackbar",
    "happing",
    "joker",
    "ive",
    "ll",
    "morpheus",
    "badchoice",
    "mmm",
    "jetpack",
    "red",
    "mordor",
    "oprah",
    "qag",
    "remembers",
    "philoseraptor",
    "jw",
    "sad-obama",
    "sad-clinton",
    "sadfrog",
    "sad-bush",
    "sad-biden",
    "sad-boehner",
    "sarcasticbear",
    "dwight",
    "sb",
    "ss",
    "sf",
    "dodgson",
    "sohot",
    "awesome-awkward",
    "awkward-awesome",
    "awkward",
    "awesome",
    "fetch",
    "success",
    "ski",
    "officespace",
    "interesting",
    "toohigh",
    "bs",
    "both",
    "winter",
    "xy",
    "buzz",
    "yodawg",
    "yuno",
    "yallgot",
    "bad",
    "elf",
    "chosen"
]

days = [
    "It's monday :cry:",
    "Today is tuesday!",
    "IT'S WEDNESDAY, MY DUDES!",
    "It's thuursday",
    "It's Rebecca Black's favorite day :wink:",
    "It's Saturday :3",
    "Monday is tomorrow :c",
]

hangman_words = [
    "frisk",
    "chara",
    "goatmom",
    "toriel",
    "asgore",
    "dreemur",
    "asriel",
    "flowey",
    "annoying dog",
    "sans",
    "papyrus",
    "undyne",
    "alphys",
    "mettaton",
    "gaster",
    "aaron",
    "astigmatism",
    "chilldrake",
    "dogamy",
    "dogaressa",
    "endogeny",
    "glyde",
    "lesser dog",
    "greater dog",
    "gyftrot",
    "ice cap",
    "jerry",
    "knight knight",
    "lemon bread",
    "loox",
    "mad dummy",
    "madjick",
    "memoryhead",
    "migosp",
    "migospel",
    "moldbygg",
    "moldessa",
    "moldsmal",
    "monster kid",
    "muffet",
    "parsnik",
    "pyrope",
    "reaper bird",
    "royal guard",
    "shyren",
    "snowdrake",
    "so sorry",
    "temmie",
    "tsunderplane",
    "vegetoid",
    "vulkin",
    "whimsalot",
    "whimsun",
    "woshua"
    "froggit",
    "napstablook",
    "megalovania",
    "human",
    "monster",
    "soul"
]

hangman_art = [
    "`|    _______   |`\n`|    |     |   |`\n`|          |   |`\n`|          |   |`\n`|         /|   |`\n`|        / |   |`",
    "`|    _______   |`\n`|    |     |   |`\n`|    O     |   |`\n`|          |   |`\n`|         /|   |`\n`|        / |   |`",
    "`|    _______   |`\n`|    |     |   |`\n`|    O     |   |`\n`|    |     |   |`\n`|         /|   |`\n`|        / |   |`",
    "`|    _______   |`\n`|    |     |   |`\n`|    O     |   |`\n`|   /|     |   |`\n`|         /|   |`\n`|        / |   |`",
    "`|    _______   |`\n`|    |     |   |`\n`|    O     |   |`\n`|   /|\\    |   |`\n`|         /|   |`\n`|        / |   |`",
    "`|    _______   |`\n`|    |     |   |`\n`|    O     |   |`\n`|   /|\\    |   |`\n`|   /     /|   |`\n`|        / |   |`",
    "`|    _______   |`\n`|    |     |   |`\n`|    O     |   |`\n`|   /|\\    |   |`\n`|   / \\   /|   |`\n`|        / |   |`"
]

kaomoji = [
    "▼=ΦωΦ=▼",
    "(ó㉨ò)ﾉ♡",
    "(-̩__-̩)",
    "(❁´◡`❁)",
    "￢o(￣-￣ﾒ)",
    "(￣(∵エ∵)￣)",
    "✖‿✖",
    "ᕙ(⇀‸↼‶)ᕗ",
    "(°ヘ°)",
    "ヾ(*￣O￣)ツ",
    "(◐‿◑)﻿",
    "(✿◠‿◠)",
    "(″･ิ_･ิ)っ",
    "ᶘ ᵒᴥᵒᶅ",
    "(づ￣ ³￣)づ",
    "(☄ฺ◣д◢)☄ฺ",
    "・㉨・",
    "(=ＴェＴ=)",
    "（=´∇｀=",
    "(／(ｴ)＼)",
    "⊙﹏⊙",
    "ミ●﹏☉ミ",
    "＿〆(。。)",
    "(-’๏_๏’-)",
    "<(￣︶￣)>",
    "๏[-ิ_•ิ]๏",
    "ヾ(´〇｀)ﾉ",
    "(╯ಊ╰)",
    "(╯_╰)",
    "Σ(￣。￣ノ)",
    "（／_＼）",
    "(╥_╥)",
    "(=^_^=)",
    "ლ(╹◡╹ლ)",
    "(。_＋)",
    "(⋋▂⋌)",
    "( • ̀ω•́ )",
    "(•ิ_•ิ)",
    "ʕ •́؈•̀ ₎",
    "(✪◡✪)",
    "‾̴̴͡͡ ▿ ‾̴̴͡͡",
    "(✘o✘)",
    "(〃･ิ‿･ิ)ゞ",
    "(•̥̀ ̫ •̥́)",
    "(≧‿≦)",
    "(〃ω〃)",
    "(｡◕ˇ‿ˇ◕｡)",
    "ต(≋°ัω°ั≋)ต",
    "ლ(❤ʚ❤ლ)",
    "(\___(\ ☂",
    "ʕ•̫͡•ʔ❤ʕ•̫͡•ʔ",
    "ต(≋°ัω°ั≋)ต",
    "ﾍ(+＿+ﾍ)",
    "／人◕‿‿◕人＼",
    "( ’◉◞౪◟◉`)",
    "(ﾐ◎-◎)ﾉ",
    "／人◕ ‿‿ ◕人＼",
    "ლ(╹◡╹ლ)",
    "╭( •̀؁•́ )╮",
    "(㇏(•̀ᵥᵥ•́)ノ)",
    "(ﾉ●◉▽◉●)ﾉ",
    "ლ(●ʘ‿ʘ● ლ)",
    "( ’◉◞౪◟◉`)",
    "/＼ ^._.^ ／\\",
    "ლ(◉◞౪◟◉ )ლ　",
    "ლ(･ิω･ิლ)",
    "꒰ू ऀ•̥́ꈊ͒ੁ•ૅू॰˳ऀ꒱ ͟͟͞ ̊ ̥ ̥",
    "ლ(⁰⊖⁰ლ)",
    "ლ(╹ε╹ლ)",
    "(๑• .̫ •๑)",
    "ʕ♡˙ᴥ˙♡ʔ",
    "ʕ≧ᴥ≦ʔ",
    "ʕ´•ᴥ•`ʔ",
    "ʕᴥ• ʔ☝",
    "(⁀ᗢ⁀)",
    "(ŏ﹏ŏ)",
    "(｡•ˇ‸ˇ•｡)",
    "(✧◑็அ◑็✧)❤",
    "(ó㉨ò)ﾉ♡",
    "凸(━へ━)",
    "凸(｀0´)凸",
    "(･_･ ) ( ･_･)",
    "(━┳━ _ ━┳━)",
    "[^._.^]ﾉ彡",
    "凸(｀⌒´メ)凸",
    "(•.•ิ)",
    "ᕦ(ò_óˇ)ᕤ",
    "(ノಠ益ಠ)ノ",
    "(〠_〠)",
    "ლ(´ڡ`ლ)",
    "(=^・ェ・^=)",
    "⁝⁞⁝⁞ʕु•̫͡•ʔु☂⁝⁞⁝⁝",
    "(｀ ・ ω ・ ‘)",
    "( -_-)凸",
    "(づ｡◕‿‿◕｡)づ",
    "(づ￣ ³￣)づ",
    "(◣_◢)",
    "(●♡∀♡)",
    "༼ ༎ຶ ෴ ༎ຶ༽",
    "༼´༎ຶ ۝ ༎ຶ༽",
    "(•ˋ _ ˊ•)",
    "⊂(￣(ｴ)￣)⊃",
    "(◕㉨◕✿)",
    "( ❝̆ ·̫̮ ❝̆ )✧",
    "(◡‿◡✿)",
    "(✧≖‿ゝ≖)",
    "(゜。゜)",
    "(*｀へ´*)",
    "(◕‿◕✿)",
    "（▼へ▼メ）",
    "ヾ(-_- )ゞ",
    "ᕙ(⇀‸↼‶)ᕗ",
    "(º_º)",
    "(⊙_◎)",
    "(￣(エ)￣)",
    "(✖╭╮✖)",
    "＜(。_。)＞",
    "m(._.)m",
    "(=ＴェＴ=)",
    "(●￣(ｴ)￣●)",
    "༼´◓ɷ◔`༽",
    "(✪ ㉨ ✪)",
    "( ´ ▽ ` )ﾉ",
    "~(=^‥^)ノ",
    "(￣▼￣)",
    "(=^･ｪ･^=)",
    "༼ꉺ.̫ꉺ༽",
    "༼ꉺ✺ꉺ༽",
    "༼ƪɷ∫༽",
    "٩◔̯◔۶",
    "༼*☁ɷ☁*༽",
    "༼ꉺ✪ꉺ༽",
    "༼ꉺεꉺ༽",
    "(ಥ﹏ಥ)",
    "༼•̃͡ ɷ•̃͡༽",
    "༼๑ɷ๑༽",
    "ミ(° °)ミ",
    "(´ε｀ )♡",
    "ʕ•̀ω•́ʔ✧",
    "(｡♥‿♥｡)",
    "༼ꉺ.̫ꉺ༽",
    "༼☉ɷ⊙༽",
    "(•ิ_•ิ)",
    "༼•̀ɷ•́༽",
    "（＾ｖ＾）",
    "●～*",
    "༼=ꉺ✺ꉺ=༽",
    "(^-人-^)",
    "(•ˋ _ ˊ•)",
    "( ^-^)_旦””",
    "٩꒰ ˘ ³˘꒱۶~♡",
    "(^._.^)ﾉ",
    "ლ(╹◡╹ლ)",
    "༼இɷஇ༽",
    "( ༎ຶ ۝ ༎ຶ )",
    "ヽ(*⌒∇⌒*)ﾉ",
    "༼❁ɷ❁༽"
]

dancers = [
    ["( ﾉ^ω^)ﾉ", "ヽ(^ω^ヽ )"],
]
